# Generated by Django 2.0 on 2019-08-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainLicense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='seq',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
